name: Run tests

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
  
jobs:
   test:
    uses: kaltura/playkit-js-common/.github/workflows/test.yml@master
    secrets: inherit
